language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3.5-5.8.0
install:
    - pip install -U setuptools pip
    - pip install -U coveralls coverage
    - pip install -U -e .[test]
script:
    - coverage run -m zope.testrunner --test-path=src
after_success:
    - coveralls
notifications:
    email: false
cache: pip
