language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3.5-5.8.0
install:
    - pip install -U setuptools pip
    - pip install -U coveralls coverage
    - pip install -U -e .[test]
script:
    - zope-testrunner --test-path=src
notifications:
    email: false
cache: pip
